# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=100)),
                ('dinner', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('guests_count', models.IntegerField()),
                ('rsvp_date', models.DateTimeField(blank=True, null=True)),
                ('rsvp', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gala.Invitee'),
        ),
        migrations.AddField(
            model_name='guest',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gala.Invitee'),
        ),
        migrations.AddField(
            model_name='dinner',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gala.Invitee'),
        ),
    ]
