# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='creator',
        ),
        migrations.AddField(
            model_name='message',
            name='user_for',
            field=models.ManyToManyField(to='loginReg.User'),
        ),
    ]
