# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20170310_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='accepter',
            new_name='friend',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='requester',
            new_name='user',
        ),
    ]
